### PR TITLE
Add jsonpb option to disable HTML scaping

### PR DESCRIPTION
**Pull request by antoniomo**
Helps fixing:

- https://github.com/gogo/protobuf/issues/484
- https://github.com/grpc-ecosystem/grpc-gateway/issues/566 via
https://github.com/gogo/gateway

Upstream issue: https://github.com/golang/protobuf/pull/409

Original upstream patch by Paul Nichols (@pauln) here:
https://github.com/golang/protobuf/pull/409

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
Hm, I can see that this wasn't merged upstream, so should we really merge this here?

**Comment by antoniomo** [comment]
I guess it depends on the desired solution for https://github.com/gogo/protobuf/issues/484?

As an alternative it can live as an external package, as a `gogo/protobuf/jsonpb` replacement. The caveat is that it makes it harder to use with other packages that just go "here" for the gogo jsonpb functionality.

**Comment by johanbrandhorst** [comment]
> I guess it depends on the desired solution for #484?
> 
> As an alternative it can live as an external package, as a `gogo/protobuf/jsonpb` replacement. The caveat is that it makes it harder to use with other packages that just go "here" for the gogo jsonpb functionality.

Thanks for the explanation. I'm not super experienced with managing this repo, so I'm going to err on the side of caution and reject this PR for now. Could you update the issue with link to your own solution for those looking for an answer? Thanks and sorry for the silence on this PR and inconvenience.

**Comment by antoniomo** [comment]
No problem, that's understandable. I'll keep my fork with the branch so other's can use this PR as reference workaround, and perhaps keep a standalone jsonpb package with just the jsonpb code.

**Pull request closed without merging**
