### PR TITLE
Test with latest Go patch versions

### PR DESCRIPTION
**Pull request by AlekSi**

### CODE REVIEW

**Comment by awalterschulze** [comment]
If we do this we also need to update the Readme.md which currently mentions specific go versions.

**Comment by AlekSi** [comment]
PTAL

**Comment by awalterschulze** [comment]
Awesome :)

Please change 3.4.1 to 3.4.0 since 3.4.1 does not have a proper download link and rebuilding protoc from source is very slow, as you can see with protoc 2.6.1

**Comment by AlekSi** [comment]
PTAL :)

**Comment by awalterschulze** [comment]
Nice thank you :)

**Pull request merged**
