### PR TITLE
options to not generate xxx fields

### PR DESCRIPTION
**Pull request by awalterschulze**
While regenerating katydid's code, I ran into a problem where goderive now regenerated its functions to take into account the new fields.
This meant that deriveCompare and deriveHash now need to also compare and hash the sizecache and unkeyed fields, the unkeyed field is not so much of a problem, but the sizecache field breaks the intent of the compare and hash functions.

Here is a proposed solution, but I am open to further discussions.

I also tested this solution on katydid and with this option, everything works.

### CODE REVIEW

**Comment by donaldgraham** [comment]
@jmarais, please review and merge if you're happy.

**Comment by awalterschulze** [comment]
This is ready to merge.
The failure is because gogoprotobuf needs to upgrade to go1.11 for the gopherjs part of the build to work.
This can be fixed with the following diff, but that should probably be a separate commit:

```
diff --git a/.travis.yml b/.travis.yml
index 8ec6af6..e9e02e9 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -18,5 +18,5 @@ script:
 language: go

 go:
-  - 1.9.x
   - 1.10.x
+  - 1.11.x
diff --git a/Makefile b/Makefile
index a66b863..bbc5397 100644
--- a/Makefile
+++ b/Makefile
@@ -167,7 +167,7 @@ contributors:
        git log --format='%aN <%aE>' | sort -fu > CONTRIBUTORS

 js:
-ifeq (go1.10, $(findstring go1.10, $(GO_VERSION)))
+ifeq (go1.11, $(findstring go1.11, $(GO_VERSION)))
        go get -u github.com/gopherjs/gopherjs
        gopherjs build github.com/gogo/protobuf/protoc-gen-gogo
 endif
```

**Comment by donaldgraham** [comment]
@jmarais has updated master with the changes you've suggested.  @awalterschulze, please could you sync your master and push.  Then  the checks on this pull request should pass.

**Comment by awalterschulze** [comment]
Thanks, I just pushed the updated branch.  I hope it works :)

**Pull request merged**
