### PR TITLE
Add stable_marshaler option to marshal deterministically

### PR DESCRIPTION
**Pull request by tamird**
This is needed to support exotic use cases where deterministic
marshalling is needed.

See https://github.com/cockroachdb/cockroach/issues/5090.

@awalterschulze I'm happy to bike shed on the option name - maybe something like "deterministicmarshal" would be better and more general? Your call.

cc @vivekmenezes @tschottdorf

### CODE REVIEW

**Comment by awalterschulze** [comment]
I like stablemarshal :)

I don't know if it needed as a field option though?
I would think your message would generate a MarshalTo method that is either stable or not.
I don't see a more find grained use case, but what do you think?  

Also I think the only thing that is causing the unstable marshal and that is maps, or am I missing something?

**Comment by awalterschulze** [comment]
Also if we go the message option route then sortmarshaler is probably more consistent.

**Comment by tamird** [comment]
Yep, it's only maps. Changed to a message-level option as you suggested. PTAL

**Comment by awalterschulze** [comment]
LGTM.
Do you know why are the travis tests not running?

**Comment by tamird** [comment]
No idea :(

**Comment by awalterschulze** [comment]
Ok it looks like they ran on travis, but they just are not displaying here anymore

**Comment by awalterschulze** [comment]
Its probably a small github bug with the new review look.  They'll probably fix it soon enough.

**Comment by tamird** [comment]
Cool beans. You can have my copyright, as usual.

**Comment by awalterschulze** [comment]
Are you ok with giving over your copyright for this pull request?

**Comment by tamird** [comment]
Yep.

**Comment by awalterschulze** [comment]
Thank you for your work :)

**Comment by tamird** [comment]
Thanks!

**Comment by awalterschulze** [comment]
I think this was probably a record for our most efficient interaction :)

**Comment by tamird** [comment]
Agreed!

**Pull request merged**
