### PR TITLE
JSON support for google.protobuf.ListValue, Struct, Value.

### PR DESCRIPTION
**Pull request by atombender**
* Fix for `google.protobuf.ListValue` being serialized as an object `{"values": [1, 2, 3]}` instead of an array `[1, 2, 3]`.

* Implements unmarshaling of `Struct`, `Value`, `ListValue`. Code ported from [PR](https://github.com/golang/protobuf/pull/208) to `golang/protobuf` (credit goes to @AmandaCameron).

### CODE REVIEW

**Comment by atombender** [comment]
FWIW, the tests pass locally. Travis renders a blank page when I try to see how the build failed, looks like a CDN issue.

**Comment by awalterschulze** [comment]
Go1.5 and Go1.6
```
go vet ./...
jsonpb/jsonpb_test.go:498: types.Value_BoolValue composite literal uses unkeyed fields
jsonpb/jsonpb_test.go:502: types.Value_StringValue composite literal uses unkeyed fields
jsonpb/jsonpb_test.go:509: types.Value_NumberValue composite literal uses unkeyed fields
jsonpb/jsonpb_test.go:510: types.Value_NumberValue composite literal uses unkeyed fields
jsonpb/jsonpb_test.go:511: types.Value_NumberValue composite literal uses unkeyed fields
exit status 1
```

**Comment by awalterschulze** [comment]
But this pull request should be done on golang/protobuf and not gogo/protobuf.
This part fix should then be merged from golang/protobuf, since gogo/protobuf is a fork of golang/protobuf and this is common code.

**Comment by atombender** [comment]
@awalterschulze There is already [an open PR in `golang/protobuf`](https://github.com/golang/protobuf/pull/208) which is what I forward-ported changes from. However, that PR also touches other, unrelated things which have not been discussed or merged.

Updated with fix for `go vet` issues`

**Comment by awalterschulze** [comment]
I think we should wait for that to be merged.  I want to see how Google fixes this.

**Pull request closed without merging**
