### PR TITLE
Compile time warning when both Sizer and Protosizer are used

### PR DESCRIPTION
**Pull request by johanbrandhorst**
Fixes issue #222

### CODE REVIEW

**Comment by awalterschulze** [comment]
Perfect :)

**Comment by awalterschulze** [comment]
Ah wait no.

This still requires an entry in the top level Makefile to actually call the test.

**Comment by johanbrandhorst** [comment]
I thought about that, but it will be called by `go test ./...`, so it shouldn't be needed?

**Comment by awalterschulze** [comment]
Ah my bad.
Context switching between projects can be tiring.
Thank you for keeping this sane :)

**Pull request merged**
