### PR TITLE
Address issue #277

### PR DESCRIPTION
**Pull request by lnshi**

### CODE REVIEW

**Comment by awalterschulze** [comment]
So the idea is that you create this as your own vanity binary in your own repo.
Its kind of hard to decide which vanity binaries to create and what combination of options they will contain.  For example lots of people don't use bson. But if you create your own binary then you have the freedom to do exactly what you want.  And it should be pretty easy to maintain.  I mean there is no reason why this cannot all live in one main.go file that simply imports gogoprotobuf.

**Comment by lnshi** [comment]
Ah, sorry, I guess I just spammed ur email, sorry, I am gonna close this. Just because I found if I want to run the tests against my fork, I need to change lots of import paths...

Understand, but can we consider to make this a command option? so people can choose there....

**Comment by lnshi** [comment]
And @awalterschulze, can u do me a bit more favour, I just cannot figure out why the last test sets always fails, checked the logs, just cannot find helpful info...

**Comment by awalterschulze** [comment]
govet is saying the struct tag's syntax is broken, but I can't spot the problem
```
test/fuzztests/fuzz.pb.go:50: struct field tag `protobuf:"fixed64,1,rep,packed,name=Field1,json=field1" json:"Field1,omitempty" bson: "Field1,omitempty"` not compatible with reflect.StructTag.Get: bad syntax for struct tag value
```
And then you just need to regenerate all the code, `make regenerate` for protoc 3.2.0

**Comment by awalterschulze** [comment]
At some point you are going to need your own test setup :)

**Comment by awalterschulze** [comment]
That bash `if` means that only for go 1.8 and protoc 3.1.0 make sure that the generated code is the code that is check it by doing a git diff after the code has been regenerated.

**Comment by awalterschulze** [comment]
I am can put a link from my documentation to your protoc binary on github for people who want bson encoding.  What do you think?

**Comment by lnshi** [comment]
@awalterschulze how come only for that test case there is one extra space coming after the bson:

**Comment by awalterschulze** [comment]
Which test are we talking about?

**Pull request closed without merging**
