### PR TITLE
Generate errcheck-passing code

### PR DESCRIPTION
**Pull request by tamird**

### CODE REVIEW

**Comment by awalterschulze** [comment]
Good catch.
Thank you very much.

Could you please just clean up the import diffs.

And then also add your errcheck test, which I think you just forgot to add.

And are you ok with giving over your copyright?

**Comment by tamird** [comment]
> Could you please just clean up the import diffs.

That was done automatically by [goimports](https://github.com/bradfitz/goimports) - I could undo it, but is it worth it?

> And then also add your errcheck test, which I think you just forgot to add.

What do you mean? I added it to the Makefiles. `errcheck` itself is a [separate project](https://github.com/kisielk/errcheck).

> And are you ok with giving over your copyright?

Yep!

**Comment by awalterschulze** [comment]
Ok my bad.

Could we keep errcheck as a seperate make job in the top level Makefile.
I don't want to add any dependencies.

errcheck:
  go install github.com/kisielk/errcheck
  errcheck ./test/...

**Comment by tamird** [comment]
Done.

**Comment by awalterschulze** [comment]
Awesome Thanks.

**Pull request merged**
