### PR TITLE
Add Travis CI check that all files are regenerated

### PR DESCRIPTION
**Pull request by tamird**
Removed protoc-gen-gogo/testdata/my_test/test.pb.go.golden because this
check supercedes the need for a "golden" file.

### CODE REVIEW

**Comment by awalterschulze** [comment]
Awesome. I have wanted to do this for years.

What happened to 
protoc-gen-gogo/testdata/my_test/test.pb.go
?

What version of protoc are you using?
I have noticed mine does not generate JsonName in the Description() method, maybe I am still on 3.0.0 alpha.

**Comment by awalterschulze** [comment]
Are you ok with giving over your copyright for this pull request?

**Comment by tamird** [comment]
Yes. `protoc` 3.0.0-beta2

**Comment by awalterschulze** [comment]
Ok and the other questions?

**Comment by awalterschulze** [comment]
protoc3 beta2 definitely fixes my problem thank you :)

**Comment by tamird** [comment]
> What happened to
protoc-gen-gogo/testdata/my_test/test.pb.go
?

I'm not sure - I cleared all the generated files and this one was not
regenerated.

**Comment by tamird** [comment]
Rebased.

**Comment by tamird** [comment]
OK, `protoc-gen-gogo/testdata/my_test/test.pb.go` is back - it just wasn't hooked up to the `regenerate` target.

**Comment by awalterschulze** [comment]
Looks perfect :)
Are you ok with giving over your copyright for this pull request?

**Comment by tamird** [comment]
yep

**Comment by awalterschulze** [comment]
Thank you so much :)

**Pull request merged**
