### PR TITLE
Exact slice allocation for repeated packed varints

### LINKED ISSUE #436: Unmarshal allocates twice the memory needed for repeated fields
The generated code that deserializes a repeated field is essentially:

    xs := make([]type, 0)
    for _, x := range things {
        xs = append(xs, x)
    }

When the Go runtime needs to grow the backing array of a slice, it uses a doubling strategy to do so.  If we have _n_ elements to append to an empty slice, and _k_ is such that _2^k < n < 2^{k+1}_, then this means we usually end up allocating space for at least

    1 + 2 + 4 + ... + 2^{k+1} = 2 * 2^{k+1}

elements, while making a single allocation of _n_ elements would have been enough.

When we deserialize a protobuf message with a packed repeated field, we know how many elements we're going to deserialize and can allocate all the memory needed in one go. [Here](https://github.com/gunnihinn/protobuf-alloc) is a demonstration of a simple program that does this. Profiling its memory use with the default generated code, and also with a single ad-hoc patch that performs this allocation, shows that what we describe above really does happen.

I work for Booking.com, and we're very interested in making this deserialization code more clever about its allocations if possible and acceptable to the maintainers. We use this library in our implementation of a [Graphite server](https://github.com/go-graphite/carbonapi), and Unmarshal is responsible for the vast majority of its memory use (around 20 GB when things are calm), which is unsurprising as the server spends most of its time deserializing very large arrays of doubles.  Getting rid of this behaviour would cut our memory use by about half.

## Sample results from running the [above program](https://github.com/gunnihinn/protobuf-alloc):

```
## Commit 36a0ed7 (current behaviour):

$ ./protobuf-alloc
$ go tool pprof protobuf-alloc memory.prof
File: protobuf-alloc
Type: inuse_space
Time: Jul 24, 2018 at 12:01pm (CEST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top                                                                                                                                                                  
Showing nodes accounting for 5175.25MB, 100% of 5175.25MB total                                                                                                              
      flat  flat%   sum%        cum   cum%
 2871.24MB 55.48% 55.48%  2871.24MB 55.48%  github.com/gunnihinn/protobuf-alloc/foo.(*Foo).Unmarshal
    2048MB 39.57% 95.05%  5175.25MB   100%  main.main
  256.01MB  4.95%   100%   256.01MB  4.95%  github.com/gunnihinn/protobuf-alloc/foo.(*Foo).Marshal
         0     0%   100%  5175.25MB   100%  runtime.main

## Commit 97163c0 (with ad-hoc allocation patch):

$ ./protobuf-alloc
$ go tool pprof protobuf-alloc memory.prof                                                                                         
File: protobuf-alloc                                                                                                                                                         
Type: inuse_space
Time: Jul 24, 2018 at 12:03pm (CEST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top                                                                                                                                                                  
Showing nodes accounting for 2304.01MB, 100% of 2304.01MB total                                                                                                              
      flat  flat%   sum%        cum   cum%
    2048MB 88.89% 88.89%  2304.01MB   100%  main.main
  256.01MB 11.11%   100%   256.01MB 11.11%  github.com/gunnihinn/protobuf-alloc/foo.(*Foo).Marshal
         0     0%   100%  2304.01MB   100%  runtime.main
```

### PR DESCRIPTION
**Pull request by mansimarkaur**
Resolves #436

### CODE REVIEW

**Comment by awalterschulze** [comment]
Very cool.
Would you mind sharing the benchmark results that you get with and without the change?

**Comment by jkucharczyk** [comment]
@awalterschulze 
Hey, here's the benchmark result (on branches rebased to master vs ours)
screen shot 2018-09-10 at 14 56 08

**Comment by mansimarkaur** [comment]
Hey! @jmarais I regenerated the branch and pushed the `*.pb.go` files. The build is still failing. 
On my local, I don't see the diff that is being generated when Travis CI runs.  Could you please help?

**Comment by awalterschulze** [comment]
Which protoc version are you running?
Gogoprotobuf is currently running 3.5.1
Maybe it is time to upgrade to running 3.6.1

**Comment by mansimarkaur** [comment]
I'm using protoc 3.6.1.

**Comment by jmarais** [comment]
> Maybe it is time for gogoprotobuf to upgrade to running 3.6.1
yup.

>  5% increase in speed and never has a negative impact.
Yes, It looks good. 
Cool.

**Pull request merged**
