### PR TITLE
added nil check in Proto/Size methods fix #444

### LINKED ISSUE #444: Size method panic   when rpc method panic !
when  rpc method panic  I can recover panic in method defer func.but because the response point is nil ,so Size method panic . like this:

`func (s *server) SayHello(ctx context.Context, in *pb.HelloRequest) (*pb.HelloReply, error) {
	defer func() {
		if r := recover(); r != nil {
			log.Println(string(debug.Stack()))
		}
	}()
	panic("test")
	return &pb.HelloReply{}, nil
}

func main() {
	lis, err := net.Listen("tcp", port)
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	s := grpc.NewServer()
	pb.RegisterGreeterServer(s, &server{})
	// Register reflection service on gRPC server.
	reflection.Register(s)
	if err := s.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}`

stack debug

goroutine 35 [running]:
github.com/myonlyzzy/go-exmaple/examples/helloworld/helloworld.(*HelloReply).Size(0x0, 0xc4202237d8)
	/Users/myonlyzzy/go/src/github.com/myonlyzzy/go-exmaple/examples/helloworld/helloworld/helloworld.pb.go:317 +0x22
github.com/myonlyzzy/go-exmaple/examples/helloworld/helloworld.(*HelloReply).Marshal(0x0, 0x14cf540, 0x0, 0x1e60048, 0x0, 0xd79573501)
	/Users/myonlyzzy/go/src/github.com/myonlyzzy/go-exmaple/examples/helloworld/helloworld/helloworld.pb.go:219 +0x2f
google.golang.org/grpc/encoding/proto.codec.Marshal(0x14cf540, 0x0, 0x0, 0xc420223908, 0x100ed6d, 0xc420010000, 0x148c760)
	/Users/myonlyzzy/go/src/google.golang.org/grpc/encoding/proto/proto.go:70 +0x19e
google.golang.org/grpc.encode(0x1e60000, 0x1812e10, 0x14cf540, 0x0, 0x1812e10, 0xc4201cc968, 0xc420210050, 0xc420210030, 0xc4201ac4a8)
	/Users/myonlyzzy/go/src/google.golang.org/grpc/rpc_util.go:487 +0x61
google.golang.org/grpc.(*Server).sendResponse(0xc420182380, 0x1581520, 0xc4200f0200, 0xc4201e8000, 0x14cf540, 0x0, 0x0, 0x0, 0xc42020c048, 0x0, ...)
	/Users/myonlyzzy/go/src/google.golang.org/grpc/server.go:830 +0x89
google.golang.org/grpc.(*Server).processUnaryRPC(0xc420182380, 0x1581520, 0xc4200f0200, 0xc4201e8000, 0xc4201842d0, 0x17e31d0, 0x0, 0x0, 0x0)
	/Users/myonlyzzy/go/src/google.golang.org/grpc/server.go:1035 +0x5df
google.golang.org/grpc.(*Server).handleStream(0xc420182380, 0x1581520, 0xc4200f0200, 0xc4201e8000, 0x0)
	/Users/myonlyzzy/go/src/google.golang.org/grpc/server.go:1248 +0x1318
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42009a640, 0xc420182380, 0x1581520, 0xc4200f0200, 0xc4201e8000)
	/Users/myonlyzzy/go/src/google.golang.org/grpc/server.go:680 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/myonlyzzy/go/src/google.golang.org/grpc/server.go:678 +0xa1

**the line 317** 
func (m *HelloReply) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovHelloworld(uint64(l))
	}
	return n
}

len(m.Name) panic because m is nil.

how to  solve this problem?

### PR DESCRIPTION
**Pull request by jmarais**

### CODE REVIEW

**Comment by awalterschulze** [comment]
Hmm actually wait on the second.
One more thing.

What happens when a nil message is passed to `proto.Size` ?

**Comment by awalterschulze** [comment]
Ok cool then we are consistent :)
I approve this pull request.

**Comment by antoniomo** [comment]
Hi,

Sorry in advance, not sure if this is the right PR or issue to comment, or if I should open a new one.

Anyway I'm having a problem with `gogo` since the update from 1.0.0, in particular, with WKT, I can't `return nil, nil` anymore as the marshalling panics. A dummy example:

```golang
func (s *service) example(*types.Empty, error) {
    return nil, nil // this works with gogo 1.0.0, not anymore
}
```

I can fix it returning `&types.Empty{}, nil` but that doesn't look so idiomatic anymore
and besides, with normal google protobuf, `return nil, nil` works.

This is the error I get with gogo 1.1.0 and 1.1.1, as well as master:

```
workspace/vendor/github.com/gogo/protobuf/types.(*Empty).Size(...)
        /go/src/workspace/vendor/github.com/gogo/protobuf/types/empty.pb.go:269
```

This was solved with this PR.

But now the panic is on `MarshalTo`:

```
workspace/vendor/github.com/gogo/protobuf/types.(*Empty).MarshalTo(...)
        /go/src/workspace/vendor/github.com/gogo/protobuf/types/empty.pb.go:171
```
Maybe I'm doing something wrong elsewhere? Just thought I would comment it here as this PR partially fixes it. 
Perhaps `plugin/marshalto/marshalto.go` can benefit of a nil check like Size, or perhaps the recommended usage is to just `return &type{}, nil`, but noting that vanilla `golang/protobuf` behaves differently.

**Comment by antoniomo** [comment]
Ignore my comment, @johanbrandhorst explained to me on slack that, while https://github.com/grpc/grpc-go/issues/532 allows `return nil, nil`, it's not the recommended usage and the type should be marshallable. Thanks!

**Pull request merged**
