### PR TITLE
Fix text unmarshal for (u)int(8/16) fields

### PR DESCRIPTION
**Pull request by aspcartman**
Consider the following proto:
```
option (gogoproto.testgen_all) = true;
message Message {
    uint32 field = 1 [(gogoproto.casttype) = "uint8"];
}
```

A completely valid proto with a valid `gogoproto.casttype`. 
But the generated tests will fail because of the inability of the text parser to parse value into (u)int(8/16). This PR fixes the issue.

### CODE REVIEW

**Comment by donaldgraham** [comment]
This is great.  Thanks. 
 
Would you mind adding a test for this?

**Comment by aspcartman** [comment]
@donaldgraham of course : ) Added as test/issue498 and verified: test fails on master branch but passes after the fix.

**Comment by aspcartman** [comment]
@donaldgraham of course : ) Added as test/issue498 and verified: test fails on master branch but passes after the fix.

**Comment by aspcartman** [comment]
@donaldgraham of course : ) Added as test/issue498 and verified: test fails on master branch but passes after the fix.

**Comment by jmarais** [comment]
Thanks for the test and the contribution. Looks good.

**Pull request merged**
