### PR TITLE
add de-duping of custom imports

### PR DESCRIPTION
**Pull request by mwitkow**
Fixes https://github.com/gogo/protobuf/issues/234 and thus https://github.com/mwitkow/go-proto-validators/issues/9

Couldn't figure out how to write a test for it though.

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
:+1:

**Comment by awalterschulze** [comment]
I don't even see any generated files that have changed. I am pretty sure I import customtypes more than once in thetest.proto 
Or maybe I am misunderstanding this patch?

**Comment by awalterschulze** [comment]
Hello?

**Comment by awalterschulze** [comment]
Closing because of inactivity, but simply make a comment if you want it reopened.

**Pull request closed without merging**
