### PR TITLE
Don't gofmt non-Go files.

### PR DESCRIPTION
**Pull request by fd**

### CODE REVIEW

**Comment by awalterschulze** [comment]
Interesting what json files are you generating?

**Comment by fd** [comment]
For now I'm just generating Swagger specifications for my GRPC/HTTP gateway.
But other things will follow. (things like: authz policies, etc...)

**Comment by awalterschulze** [comment]
Wow have you open sourced it?

**Comment by fd** [comment]
No not yet. It's really a toy implementation for now. But open sourcing the generator is definitely part of the plan.

**Comment by awalterschulze** [comment]
Why do you need to do this through the vanity binary?
It seems quite nice

**Comment by fd** [comment]
Well, I guess I don't have todo through the vanity package. Right now I'm just appending some files to the protoc response from a custom plugin.

**Comment by awalterschulze** [comment]
Sorry I have been sick for a while.
Have you made any progress without using the vanity package?

**Comment by fd** [comment]
No I haven't. I'm not sure how to make a non-vanity plugin.

**Comment by awalterschulze** [comment]
Basically you do exactly what you did in the diff here, but you just copy it into your own library and create your own binary.  The only reason I am suggesting this is because I think its niche enough to justify a copy.

**Comment by awalterschulze** [comment]
I suspect I can close this.

**Pull request closed without merging**
