### PR TITLE
Expose vanity TurnOnRegistration

### PR DESCRIPTION
**Pull request by Tommy-42**
close https://github.com/gogo/protobuf/issues/401

### CODE REVIEW

**Comment by awalterschulze** [comment]
Could you change the function name to `TurnOnGoRegistration` ?

The other problem is that there is a diff with go 1.10 when the code is gofmted.
This is solved on the `dev` branch, which should be merged in next couple of weeks.
So you can either wait for `dev` to be merged into `master` or make a pull request on `dev`.

**Comment by Tommy-42** [comment]
Yep, done :) !

I switched to `into gogo:dev from Tommy-42:exposeVanity` 

we will point to the dev then :) ! 

Thanks for your work again

**Comment by Tommy-42** [comment]
hmm is it normal ?

**Comment by awalterschulze** [comment]
No its not normal and it is an important check.
I want to be sure the committed code is gofmted and regenerated.

You are also welcome to make a fix or wait for me to fix it when I take some time to merge the `dev` branch as well.

**Comment by awalterschulze** [comment]
Could you also change the function name to `TurnOnGoRegistration` ?

**Comment by Tommy-42** [comment]
of yes my bad I was miss reading it : `missing the `Go` part 

doing it right now

**Comment by awalterschulze** [comment]
LGTM :)

**Pull request merged**
