### PR TITLE
Add go_package

### PR DESCRIPTION
**Pull request by tomwilkie**
The expected contents of go_package has changed, see golang/protobuf#139

This is needed to build stuff with bazel - see bazelbuild/rules_go#836

### CODE REVIEW

**Comment by awalterschulze** [comment]
You also need to modify the gogoproto/Makefile

`	protoc --gogo_out=Mgoogle/protobuf/descriptor.proto=github.com/gogo/protobuf/protoc-gen-gogo/descriptor:../../../../ --proto_path=../../../../:../protobuf/:. *.proto
`

And regenerate the code.

And then it should be ready for merge.

**Comment by tomwilkie** [comment]
Thanks @awalterschulze, done that now.

**Comment by awalterschulze** [comment]
You forgot to update the Makefile I think.

**Comment by tomwilkie** [comment]
@awalterschulze should be all fixed, sorry about that.

**Comment by awalterschulze** [comment]
Cool :)
Thank you for the work.

**Comment by tomwilkie** [comment]
No worries - thank you!

**Pull request merged**
